server:
  port: 8282

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #Spring mvc?? url ?? ???? ??.
  datasource:
    url: jdbc:mysql://localhost:3306/untitled
    username: root
    password: qhdwnsgud1!
  servlet:
    multipart:
      max-file-size: 500MB    #??? ??? ??? ?? ??? 500MB? ??
      max-request-size: 550MB #?? ??? ?? ??? 500MB? ??
  messages:
    basename: message/messages  #message/messages ?????? ??? ?? ??
    encoding: utf-8             #??? ??? ???? utf-8? ??
    fallback-to-system-locale: false  #??? ???? fallback ?? ??, false?? ??? ??? ?? X
    always-use-message-format: true   #??? ??? ?? messageFormat? ????? ??



